#!/usr/bin/env python

import sys
import pycurl

class Console(object):
	_instance = None

	def __new__(cls, *args, **kwargs):
		if not cls._instance:
			cls._instance = super(Console, cls).__new__(cls,
			*args, **kwargs)
		return cls._instance

	def __init__(self):
		self.content = ""

	def buffer_content(self, buf):
		self.content += buf

	def print_content(self):
		print(self.content)

def curl_setup(word, console):
	req = pycurl.Curl()
	req.setopt(pycurl.URL,
	"dict://dict.org/d:{0}".format(word))
	req.setopt(pycurl.CONNECTTIMEOUT, 5)
	req.setopt(pycurl.TIMEOUT, 8)
	req.setopt(pycurl.FAILONERROR, True)
	req.setopt(pycurl.WRITEFUNCTION, console.buffer_content)


if __name__ == "__main__":
	if len(sys.argv) < 2:
		sys.stderr.write("Usage: define [word]")
		sys.exit(1)

	console = Console()
	curl_setup(sys.argv[1], console)

	try:
		req.perform()
		console.print_content()
	except pycurl.error, error:
		errno, errstr = error
		sys.stderr.write("Error {0}: {1}".format(errno, errstr))
